services:
  scipy-lab:
    container_name: scipy-lab
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
